apiVersion: v1
kind: ConfigMap

metadata:
  name: limes

data:
  policy.yaml: |
{{ .Files.Get "files/policy.yaml" | indent 4 }}
  limes.yaml: |
    clusters:
      ccloud:
{{ toYaml .Values.limes.clusters.ccloud | indent 8 }}
  constraints-ccloud.yaml: |
{{ toYaml .Values.limes.constraints.ccloud | indent 4 }}
